### ISSUE TITLE
Trigger GitHub Actions just on changes to either the tests or the src code

### ISSUE THREAD

**Issue by alvarobartt** [alvarobartt/investpy#285]
Currently, the GitHub Actions build is being triggered on each commit to every branch, but it just needs to be triggered whenever any change/modification is being done in either the source code under `investpy/` or the tests under `tests/`.

Should be something similar to:

```yml
on:
  push:
    paths:
      - .github/workflows/sanity.yml
      - model/**
      - tests/**
```
